---
# handlers file for joe-speedboat.nextcloud

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: reload php-fpm
  service:
    name: php-fpm
    state: reloaded

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart redis
  service:
    name: redis
    state: restarted 
...
