---
# permissions.yml

- name: ensure occ is executable
  file:
    path: '{{ nextcloud_webroot }}/occ'
    mode: a+x

- name: ensure directories exist with correct permissions
  file:
    path: '{{ item  }}'
    owner: nginx
    group: nginx
    recurse: yes
    state: directory
  with_items:
    - '{{ nextcloud_webroot }}'
    - '{{ nextcloud_dataroot }}'

- name: configure selinux settings
  block:
  - name: ensure SELinux file context mapping definitions are correct
    sefcontext:
      target: '{{ item  }}'
      setype: httpd_sys_rw_content_t
    with_items:
      - '{{ nextcloud_dataroot }}(/.*)?'
      - '{{ nextcloud_webroot }}/config(/.*)?'
      - '{{ nextcloud_webroot }}/apps(/.*)?'
      - '{{ nextcloud_webroot }}/.htaccess'
      - '{{ nextcloud_webroot }}/.user.ini'
    register: sefcontext

  - name: run restorecon if SELinux file context was changed
    command: '{{ item  }}'
    when: sefcontext.changed
    with_items:
      - 'restorecon -Rv {{ nextcloud_dataroot }}'
      - 'restorecon -Rv {{ nextcloud_webroot }}'

  - name: ensure SELinux boolean is set for redis
    seboolean:
      name: httpd_can_network_connect
      state: yes
      persistent: yes
  when: ansible_selinux.status == "enabled"
